### PR TITLE
fixes #133: same task runner for platform&render

### LINKED ISSUE #133: Segmentation fault: 11 when resizing window on MacOS
Initially screen is empty, then when I resize it - application crashes with message in issue title.
After maximizing application works fine.

### PR DESCRIPTION
**Pull request by pchampio**
rework of the last atempt: https://github.com/go-flutter-desktop/go-flutter/pull/329
Had to use a new internal package to query thread ID.
pakcage currentthread is compatible with windows (tested on the very old: gcc.exe (tdm64-1) 5.1.0) (won't have the same issue as in: https://github.com/go-flutter-desktop/go-flutter/issues/245)

### CODE REVIEW

File: event-loop.go [hunk 1]
```diff
@@ -46,17 +49,10 @@ func newEventLoop(postEmptyEvent func(), onExpiredTask func(*embedder.FlutterTas
...
 
-// RunOnCurrentThread FlutterDocs:
-//   May be called from any thread. Should return true if tasks posted on the
-//   calling thread will be run on that same thread.
-//
-// The functions PostTask and onExpiredTask should be called from the same
-// thread, this is ensured if the creation of the event loop (through
-// `newEventLoop`) and the PostTask callback (through
-// `a.engine.TaskRunnerPostTask = eventLoop.PostTask`) are done on a calling
-// goroutine which always execute in that thread (`runtime.LockOSThread()`).
```
Comment (pchampio) [inline event-loop.go:57]: This assumption was wrong.

**Review by provokateurin — APPROVED** [review]

File: internal/currentthread/thread-id.go [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+//   #else
+//     return pthread_self();
+//   #endif
+// }
+// size_t getCurrentTheradID() { return (size_t)thrd_current(); }
+import "C"
+
+// ID returns the id of the current thread
+func ID() int64 {
+	return (int64)(C.getCurrentTheradID())
```
Comment (james-lawrence) [inline internal/currentthread/thread-id.go:29]: wouldn't `syscall.Gettid()` workd?

Comment (pchampio) [reply internal/currentthread/thread-id.go:29]: I'm not sure `syscall.Gettid()` works on windows, I have tested this under wine, using [tdm-gcc](https://jmeubank.github.io/tdm-gcc/) and it worked.
I'm a but scared of `syscall.Gettid()`, if you have more experience with it, and are sure it is working well under windows, I'm all good to use it.
Ref:
https://github.com/golang/go/issues/18590#issuecomment-271632152
https://github.com/golang/go/issues/18590#issuecomment-362344496

File: internal/currentthread/thread-id.go [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+// #endif
+//
+// thrd_t thrd_current(void) {
+//   #if defined(_WIN32) || defined(__WIN32__) || defined(__WINDOWS__)
+//     return GetCurrentThread();
+//   #else
+//     return pthread_self();
+//   #endif
+// }
+// size_t getCurrentTheradID() { return (size_t)thrd_current(); }
```
Comment (GeertJohan) [inline internal/currentthread/thread-id.go:24]: Typo, s/Therad/Thread/g

**Review by GeertJohan — CHANGES_REQUESTED** [review]

File: event-loop.go (hunk 1 above)
Comment (GeertJohan) [reply event-loop.go:57]: Hmm that's interesting... I'm not sure I understand which behaved different than expected..?

Comment (pchampio) [reply event-loop.go:57]: The call to `RunOnCurrentThread` is done by the engine, on an internally managed thread.
The assumption that `runtime.LockOSThread()` would also lock on which thread this Cb is executed is wrong.

When the task_runner was only wired for `platform_task_runner`, the engine was always piking the correct thread to handle the cb.
But when adding `render_task_runner` to the same task_runner, the engine first try to run the GLFW cb (context current, swapbuffer,.. stuff defined in application.go) on an non-main thread, it's only on the seconds try (after this `RunOnCurrentThread` returned false once), that the engine select the correct thread to run those GLFW Cbs.

**Comment by GeertJohan** [comment]
LGTM, but I haven't been able to extensively test this on MacOS.

File: event-loop.go [hunk 4]
```diff
@@ -22,17 +23,19 @@ type EventLoop struct {
 
 	// timeout for non-Rendering events that needs to be processed in a polling manner
 	platformMessageRefreshRate time.Duration
+
+	// indetifer for the current thread
```
Comment (GeertJohan) [inline event-loop.go:27]: typo: identifier

**Review by GeertJohan — CHANGES_REQUESTED** [review]

**Review by GeertJohan — APPROVED** [review]

**Comment by GeertJohan** [comment]
:rocket:
