### PR TITLE
Beta

### LINKED ISSUE #102: Add support for external OpenGL textures
The flutter engine ABI supports external OpenGL textures allowing the embedder to draw to OpenGL directly. [engine#7087](https://github.com/flutter/engine/pull/7087)

It's needed to implement the [VideoPlayer](https://github.com/flutter/plugins/tree/master/packages/video_player).

### LINKED ISSUE #141: failed to decode envelope: unexpected end of JSON input
Errors like these may occur in the standard output:

```go-flutter: failed to pop route after escape key press: failed to decode envelope: unexpected end of JSON input```

This is the case because InvokeMethod always expects a response which it wants to decode, but we don't always get a response. Currently responses are not implemented (https://github.com/flutter/flutter/issues/18852), and even when they are, some methods don't return a response.

Java has `InvokeMethod` vs `InvokeMethod with callback`. Perhaps we should also provide two methods, one which doesn't expect a response and therefore doesn't try to decode it (resulting in decode error)

### LINKED ISSUE #175: Wire up custom event loop interop
The flutter/engine GLFW implementation makes use of the [` custom_task_runners`](https://github.com/flutter/engine/blob/e7f8ca1de9f714596a17fa953fad6e1791c8ce38/shell/platform/embedder/embedder.h#L678-L681).  
The implementation is available here: https://github.com/flutter/engine/commit/4e344e6cd23b2195c544d53cbad410c71534704c  , it is just a matter of porting it to go-flutter.

The use of a custom event loop interop will resolve some delay experienced by plugin author https://github.com/go-flutter-desktop/go-flutter/issues/132#issuecomment-507070367 , and it will able us to have 'true' passive sleep. (instead of fetching platform message every 0.016 seconds even when there is no message available)

### LINKED ISSUE #230: Blank Screen When Executing Async Method at Startup
how to reproduce,
change main method on main_desktop.dart with async
call an async method using await before runApp() , for exampe load SharedPreference.

run application using hover run and dont touch mouse or keyboard anymore, the application show blank screen until you move mouse inside application window or typing button on keyboard.

### PR DESCRIPTION
**Pull request by pchampio**
Review the commit on this branch as individual PR.
Regrouping:
 - #217 - fixes: #102
 - #218 - fixes: #175 
 - #220 - fixes: #141 & #183 

~test on `flutter channel master`~

last commit fixes: #230

### CODE REVIEW

**Comment by Drakirus** [comment]
The initial `glfw.WaitEvents()`(the one before the event loop) has been removed.
I didn't liked the workaround and it might be the causes to #230. 
The following warning can still occur: 
```log
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 359 pos 20: '_pointers.containsKey(datum.device)': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:359:20)
#3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:144:12)
#4      ListQueue.addAll (dart:collection/queue.dart:655:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:84:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:252:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:161:5)
```

fixes: #230

**Comment by Drakirus** [comment]
This Branch is compatible with `flutter channel beta`.
Asking for review!

File: event-loop.go [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+		// other threads to block on posting tasks onto this thread till we are
+		// done processing expired tasks.
+		expiredTasks = append(expiredTasks, top)
+
+	}
+	t.priorityqueue.Unlock()
+
+	// Fire expired tasks.
+	for _, item := range expiredTasks {
+		task := item.Value.(embedder.FlutterTask)
```
Comment (GeertJohan) [inline event-loop.go]: If our priorityqueue always contains item.Value's of type `embedder.FlutterTask`, then we could change the priorityQueue to specifically contain embedder.FlutterTask's, instead of interface{} values.

File: event-loop.go [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+		// platform messages) and not too low (heavy CPU consumption).
+		// This value isn't related to FPS, as rendering events are process in a
+		// waiting manner.
+		maxWaitDuration: time.Duration(25) * time.Millisecond,
+	}
+}
+
+// RunOnCurrentThread returns if the current thread is the thread used
+// by the GLFW event loop.
+func (t *EventLoop) RunOnCurrentThread() bool {
```
Comment (GeertJohan) [inline event-loop.go]: This is given to `engine.TaskRunnerRunOnCurrentThread`, but what if it is called from C-land on a different Thread??

Sure, Application.Run() calls `runtime.LockOSThread`, but that doesn't guarantee that the Engine doesn't start it's own threads and calls this function from then, right?

File: key-events.go [hunk 3]
```diff
@@ -81,7 +81,7 @@ func (p *keyeventPlugin) sendKeyEvent(window *glfw.Window, key glfw.Key, scancod
 		ScanCode:  scancode,
 		Modifiers: int(mods),
 	}
-	_, err := p.keyEventChannel.Send(event)
+	err := p.keyEventChannel.Send(event)
```
Comment (GeertJohan) [inline key-events.go]: Well, we are still v0.x (alpha) so breaking changes are allowed I guess.. Fix is easy and probably this isn't used often yet.

File: messenger.go [hunk 4]
```diff
@@ -48,9 +60,28 @@ func (m *messenger) Send(channel string, binaryMessage []byte) (binaryReply []by
...
-	// NOTE: Response from engine is not yet supported by embedder.
-	// https://github.com/flutter/flutter/issues/18852
-	return nil, nil
+	// wait for a reply and return
+	return <-reply, nil
+}
+
+// SendNoReply pushes a binary message on a channel to the Flutter side without
+// expecting replies.
+func (m *messenger) SendNoReply(channel string, binaryMessage []byte) (err error) {
```
Comment (GeertJohan) [inline messenger.go]: It's a bit inconsistent that the BinaryMessenger has Send and SendNoReply, but the channels have SendWithReply and Send (no reply). Perhaps change the BinaryMessenger to align with the latter?

File: event-loop.go (hunk 2 above)
Comment (Drakirus) [reply event-loop.go]: Agreed, the flutter GLFW shell uses `std::this_thread::get_id() == main_thread_id_;`
There aren't any api on golang to retrieve the current thread id, (well they are but if you use them [“If you use this package, you will go straight to hell.“](https://godoc.org/github.com/davecheney/junk/id))

Giving the facts that:
 - the engine can do the `std::this_thread::get_id() == main_thread_id_;` internally to check if he is running on his correct thread.   
- we only use one thread for the Platform Task Runner and UI Task Runner
`engine.TaskRunnerRunOnCurrentThread` [flutter/wiki](https://github.com/flutter/flutter/wiki/The-Engine-architecture#threading)
- IIRC, calls from the engine to the embedder are done in the same thread.

From my understanding of the golang language, there is no way of getting the thread_id, that why I made the choice to always return true.

If you have any proposition, please let me know!

Comment (Drakirus) [reply event-loop.go]: more info on https://github.com/flutter/engine/pull/8273#discussion_r269809503

Comment (Drakirus) [reply event-loop.go]: more info: https://github.com/flutter/engine/pull/8273#discussion_r269809503

File: application.go [hunk 5]
```diff
@@ -240,42 +263,59 @@ func (a *Application) Run() error {
...
+	windowManager.glfwRefreshCallback(a.window)
+	// Attach glfw window callbacks for refresh and position changes
+	a.window.SetRefreshCallback(windowManager.glfwRefreshCallback)
+	a.window.SetPosCallback(windowManager.glfwPosCallback)
 
-	// flutter's PlatformMessage handler is registered through the dart:ui.Window
-	// interface. ui.Window must have at least paint one frame, before any
-	// platfrom message can be corectly handled by ui.Window.onPlatformMessage.
-	glfw.WaitEvents()
+	// TODO: Can this only be done here? Why not in the plugin/glfwPlugin init loop above?
```
Comment (Drakirus) [inline application.go]: When the plugin maker gets access to the texturer, (`flutter.TextureRegistry`).
He can create a new texture `myTexture := registry.NewTexture()`, and without waiting, call `myTexture.FrameAvailable()`.

When doing so, the engine must be running and ready to process texture.

File: application.go [hunk 6]
```diff
@@ -240,42 +263,59 @@ func (a *Application) Run() error {
...
-		glfw.WaitEventsTimeout(0.016) // timeout to get 60fps-ish iterations
-		embedder.FlutterEngineFlushPendingTasksNow()
+		eventLoop.WaitForEvents(func(duration float64) {
+			glfw.WaitEventsTimeout(duration)
+		})
 		defaultPlatformPlugin.glfwTasker.ExecuteTasks()
 		messenger.engineTasker.ExecuteTasks()
 	}
 
+	// TODO: What if the window indicates to stop, but there are tasks left on
```
Comment (Drakirus) [inline application.go]: [` Running the task before that time is undefined behavior.`](https://github.com/flutter/engine/blob/6a5cbbdb4fc111b7be711e2d8bfbc8a336895c38/shell/platform/embedder/embedder.h#L1099-L1100)

Should we call `a.engine.Shutdown()` and then, process all of the event in the event loop that are `task event time < current time` ?

File: application.go (hunk 5 above)
Comment (Drakirus) [reply application.go]: Moving the init loop here can be a possibility.

File: application.go (hunk 6 above)
Comment (Drakirus) [reply application.go]: > Should we call a.engine.Shutdown() and then, process all of the event in the event loop that are task event time < current time ?

Since the engine is stopped, we cannot process the `task event time < current time`.

Comment (Drakirus) [reply application.go]: The answer to the question:
> 	// TODO: What if the window indicates to stop, but there are tasks left on
	// the queue?

Is discard them, the engine will shutdown, the loop above already processed the  `task event time < current time`.

File: glfw.go [hunk 7]
```diff
@@ -53,8 +53,6 @@ func (m *windowManager) sendPointerEvent(window *glfw.Window, phase embedder.Poi
 		return
 	}
 
-	// TODO(GeertJohan): sometimes the x and/or y given by glfw is negative or over window size, could this cause an issue?
```
Comment (Drakirus) [inline glfw.go]: x and/or y given by glfw can be negative, this occurs when the cursor is dragged (kMove) away from the window.

File: application.go (hunk 5 above)
Comment (GeertJohan) [reply application.go]: I think the init loop for plugins must happen before the engine starts, so that channels are registered before Dart code starts sending messages to the Go side.

I'm assuming any use of the testurer API will be initiated by a call from the Dart side, so the texturer wont' be used before the engine is alive.
The normal plugin init also exposes the messenger, even though it can't be used yet because the engine isn't running. So far, all plugins I've seen don't do anything until asked via message/method call.

Comment (Drakirus) [reply application.go]: > I think the init loop for plugins must happen before the engine starts, so that channels are registered before Dart code starts sending messages to the Go side.

Agree!
But, in our case it's more like `the init loop for plugins must happen before we start processing embedder.FlutterTask, so that channels are ready before the embedder starts handling platform messages to the Go side`

Platform messages aren't  processed until in the `eventLoop.WaitForEvents`, which occurs after  the plugin init loop.
```go
for !a.window.ShouldClose() {
	eventLoop.WaitForEvents(func(duration float64) { // <- Process Platform task
		glfw.WaitEventsTimeout(duration)
	})
	defaultPlatformPlugin.glfwTasker.ExecuteTasks()
	messenger.engineTasker.ExecuteTasks()
}
```
 
---

> I'm assuming any use of the testurer API will be initiated by a call from the Dart side, so the texturer wont' be used before the engine is alive.

While call to the [`handle`](https://github.com/go-flutter-desktop/examples/blob/b15e61712768e93b37934b8e68cf7975f2d0f5a9/texture_tutorial/go-texture-example/image/main.go#L46) of a `texture` is made from the engine side. Call from the Golang [`texture.FrameAvailable()`](https://github.com/go-flutter-desktop/examples/blob/b15e61712768e93b37934b8e68cf7975f2d0f5a9/texture_tutorial/go-texture-example/video/main.go#L53) to the engine can be made at any time, the engine must be running otherwise we get segfault.

Comment (Drakirus) [reply application.go]: Plugin is also used internally (by the [`textinputPlugin`](https://github.com/go-flutter-desktop/go-flutter/blob/19ec300ac7e16fc0e4b0bc4d976a646136c5f404/textinput.go#L17) for example), the plugins init loop occurs before we set the GLFW handles, it's a non-issue.

File: event-loop.go (hunk 2 above)
Comment (Drakirus) [reply event-loop.go]: Resolved using C call

File: event-loop.go [hunk 8]
```diff
@@ -23,13 +23,17 @@ type EventLoop struct {
...
+	// indetifer for the current thread
+	mainThreadID uint64
 }
 
 func newEventLoop(postEmptyEvent func(), onExpiredTask func(*embedder.FlutterTask) embedder.Result) *EventLoop {
 	pq := priorityqueue.NewPriorityQueue()
 	heap.Init(pq)
 	return &EventLoop{
 		priorityqueue:  pq,
+		mainThreadID:   embedder.GetCurrentTheradID(),
```
Comment (GeertJohan) [inline event-loop.go]: Typo `Therad`. Also: should we maybe make this function available from an internal package, not as part of the embedder package?

**Comment by GeertJohan** [comment]
Failure to compile for windows? #245

**Review by GeertJohan — APPROVED** [review]
